<?php

namespace AppBundle\Repository;

/**
 * CFARepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CFARepository extends \Doctrine\ORM\EntityRepository
{
}
