<?php

namespace AppBundle\Repository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends \Doctrine\ORM\EntityRepository
{
}
