<?php

namespace AppBundle\Repository;

/**
 * HistoricCfaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricCfaRepository extends \Doctrine\ORM\EntityRepository
{
}
