<?php

namespace AppBundle\Repository;

/**
 * PartnairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnairRepository extends \Doctrine\ORM\EntityRepository
{
}
