<?php

namespace AppBundle\Repository;

/**
 * TaxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxeRepository extends \Doctrine\ORM\EntityRepository
{
}
