<?php

namespace AppBundle\Repository;

/**
 * UfaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UfaRepository extends \Doctrine\ORM\EntityRepository
{
}
